config/routes.rb
KidsChores::Application.routes.draw do
  resources :wallets

  get "pages/home"

  get "pages/contact"

  get "pages/about"

  get "pages/help"

  resources :children do
    resources :chores
    resources :wallets
  end
  resources :chores, :controller => :chores
  
  root :to => "pages#home", :as => 'home'

end

app/models/wallet.rb
class Wallet < ActiveRecord::Base
    belongs_to :child
    belongs_to :chore

    validates :child_id, :presence => true
    validates :chore_id, :presence => true
    
    def total_value
      chore.value * quantity
    end
end

app/controllers/wallets_controller.rb
class WalletsController < ApplicationController
  # GET /wallets
  # GET /wallets.xml
  def index
    @wallets = Wallet.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @wallets }
    end
  end

  # GET /wallets/1
  # GET /wallets/1.xml
  def show
    @wallet = Wallet.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @wallet }
    end
  end

  # GET /wallets/new
  # GET /wallets/new.xml
  def new
    @wallet = Wallet.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @wallet }
    end
  end

  # GET /wallets/1/edit
  def edit
    @wallet = Wallet.find(params[:id])
  end

  # POST /wallets
  # POST /wallets.xml
  def create
    @child = Child.find(params[:child_id])
    chore = Chore.find(params[:chore_id])
    @wallet = @child.add_chore(chore.id)

    respond_to do |format|
      if @wallet.save
        #TODO NEED to fix below to redirect to child_chores_path in order for AJAX to work
        format.html { redirect_to (child_chores_path(@child)) } 
        format.js
        format.xml  { render :xml => @wallet, :status => :created, :location => @wallet }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @wallet.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /wallets/1
  # PUT /wallets/1.xml
  def update
    @wallet = Wallet.find(params[:id])

    respond_to do |format|
      if @wallet.update_attributes(params[:wallet])
        format.html { redirect_to(@wallet, :notice => 'Wallet was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @wallet.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /wallets/1
  # DELETE /wallets/1.xml
  def destroy
    @wallet = Wallet.find(params[:id])
    @wallet.destroy

    respond_to do |format|
      format.html { redirect_to(wallets_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/wallets_helper.rb
module WalletsHelper
end

app/views/wallets/_form.html.erb
<%= form_for(@wallet) do |f| %>
  <% if @wallet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@wallet.errors.count, "error") %> prohibited this wallet from being saved:</h2>

      <ul>
      <% @wallet.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :child_id %><br />
    <%= f.text_field :child_id %>
  </div>
  <div class="field">
    <%= f.label :chore_id %><br />
    <%= f.text_field :chore_id %>
  </div>
  <div class="field">
    <%= f.label :payment_status %><br />
    <%= f.check_box :payment_status %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/wallets/_wallet.html.erb
  <tr>
	<td><%= wallet.quantity %> &times;</td>
	<td><%= wallet.chore.title %></td>
	<td class="item_price"><%= number_to_currency(wallet.total_value) %></td>
  </tr>

app/views/wallets/edit.html.erb
<h1>Editing wallet</h1>

<%= render 'form' %>

<%= link_to 'Show', @wallet %> |
<%= link_to 'Back', wallets_path %>

app/views/wallets/index.html.erb
<h1>Listing wallets</h1>

<table>
  <tr>
    <th>Child</th>
    <th>Chore</th>
    <th>Payment status</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @wallets.each do |wallet| %>
  <tr>
    <td><%= wallet.child_id %></td>
    <td><%= wallet.chore_id %></td>
    <td><%= wallet.payment_status %></td>
    <td><%= link_to 'Show', wallet %></td>
    <td><%= link_to 'Edit', edit_wallet_path(wallet) %></td>
    <td><%= link_to 'Destroy', wallet, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Wallet', new_wallet_path %>

app/views/wallets/new.html.erb
<h1>New wallet</h1>

<%= render 'form' %>

<%= link_to 'Back', wallets_path %>

app/views/wallets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Child:</b>
  <%= @wallet.child_id %>
</p>

<p>
  <b>Chore:</b>
  <%= @wallet.chore_id %>
</p>

<p>
  <b>Payment status:</b>
  <%= @wallet.payment_status %>
</p>


<%= link_to 'Edit', edit_wallet_path(@wallet) %> |
<%= link_to 'Back', wallets_path %>