config/routes.rb
KidsChores::Application.routes.draw do
  resources :wallets

  get "pages/home"

  get "pages/contact"

  get "pages/about"

  get "pages/help"

  resources :children do
    resources :chores
    resources :wallets
  end
  resources :chores, :controller => :chores
  
  root :to => "pages#home", :as => 'home'

end

app/models/chore.rb
class Chore < ActiveRecord::Base
  has_many :wallets
  has_many :kids, :through => :wallet
  
  default_scope :order => 'title'
  
  validates :title, :description, :image_url, :presence => true
  validates :value, :numericality => {:greater_than_or_equal_to => 0.01}
  validates :title, :uniqueness => true
  validates :image_url, :format => {
    :with => %r{\.(gif|jpg|png)$}i,
    :message => 'must be a URL for GIF, JPG or PNG image.'
  }
end

app/controllers/chores_controller.rb
class ChoresController < ApplicationController
  # TODO add a before_filter to this controller to ensure only admins have access

  # GET /chores
  # GET /chores.xml
  def index
    @child = Child.find_by_id(params[:child_id])
    @chores = Chore.all
    #@child = Child.find_by_id(params[:child_id])
    #@chores = Chore.all
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @chores }
    end
  end

  # GET /chores/1
  # GET /chores/1.xml
  def show
    @chore = Chore.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @chore }
    end
  end

  # GET /chores/new
  # GET /chores/new.xml
  def new
    @chore = Chore.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @chore }
    end
  end

  # GET /chores/1/edit
  def edit
    @chore = Chore.find(params[:id])
  end

  # POST /chores
  # POST /chores.xml
  def create
    @chore = Chore.new(params[:chore])

    respond_to do |format|
      if @chore.save
        format.html { redirect_to(@chore, :notice => 'Chore was successfully created.') }
        format.xml  { render :xml => @chore, :status => :created, :location => @chore }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @chore.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /chores/1
  # PUT /chores/1.xml
  def update
    @chore = Chore.find(params[:id])

    respond_to do |format|
      if @chore.update_attributes(params[:chore])
        format.html { redirect_to(@chore, :notice => 'Chore was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @chore.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /chores/1
  # DELETE /chores/1.xml
  def destroy
    @chore = Chore.find(params[:id])
    @chore.destroy

    respond_to do |format|
      format.html { redirect_to(chores_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/chores_helper.rb
module ChoresHelper
end

app/views/chores/_form.html.erb
<%= form_for(@chore) do |f| %>
  <% if @chore.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@chore.errors.count, "error") %> prohibited this chore from being saved:</h2>

      <ul>
      <% @chore.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description, :rows => 6 %>
  </div>
  <div class="field">
    <%= f.label :image_url %><br />
    <%= f.text_field :image_url %>
  </div>
  <div class="field">
    <%= f.label :value %><br />
    <%= f.text_field :value %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/chores/edit.html.erb
<h1>Editing chore</h1>

<%= render 'form' %>

<%= link_to 'Show', @chore %> |
<%= link_to 'Back', chores_path %>

app/views/chores/index.html.erb
<div id="chore-list">
  <h1>Listing chores</h1>

  <table>
  <% @chores.each do |chore| %>
    <tr class="<%= cycle('list-line-odd', 'list-line-even') %>">

<%     ##TODO.. Fix to be sure to link "post" action to "show" child. %>
  	  <td>
        <%= link_to(image_tag(chore.image_url, :class => 'list-image'),
			wallets_path(:chore_id => chore, :child_id => session[:child_id]),
			{:method => :post}) %>
      </td>
	
      <td class="list-description">
        <dl>
          <dt><%=h chore.title %></dt>
          <dd><%=h truncate(chore.description.gsub(/<.*?>/,''),
                 :length => 80) %></dd>
        </dl>
      </td>

	  <td class="value">
        <dl>
          <dt><%= number_to_currency(chore.value) %></dt>
        </dl>
      </td>
	 
	  <td class="button"><%= button_to "Add to Wallet", wallets_path(:chore_id => chore, :child_id => session[:child_id]),
	 			:remote => true %></td>

      <td class="list-actions">
        <%= link_to 'Show', chore %><br/>
        <%= link_to 'Edit', edit_chore_path(chore) %><br/>
        <%= link_to 'Destroy', chore, 
                    :confirm => 'Are you sure?',
                    :method => :delete %>
      </td>
    </tr>
  <% end %>
  </table>
</div>

<br />

<%= link_to 'New chore', new_chore_path %>

app/views/chores/new.html.erb
<h1>New chore</h1>

<%= render 'form' %>

<%= link_to 'Back', chores_path %>

app/views/chores/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @chore.title %>
</p>

<p>
  <b>Description:</b>
  <%= @chore.description %>
</p>

<p>
  <b>Image url:</b>
  <%= @chore.image_url %>
</p>

<p>
  <b>Value:</b>
  <%= @chore.value %>
</p>


<%= link_to 'Edit', edit_chore_path(@chore) %> |
<%= link_to 'Back', chores_path %>